# site settings
title: Zane
subtitle: 
email: youremailaddress@gmail.com
description: This is an experiment with github pages to support my learning.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/zane-chung-mehdi
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zanecmehdi

# build settings
markdown: kramdown

sass:
  style: compressed
